{% extends "base.phtml" %}

{% block content %}
  <form id="login-form" action="index.php?page=view_leaves" method="post">
    <legend id="login-legend">Login</legend>
    <label for="UserName">Username:</label>
    <input type="TEXT" name="UserName" size="12" maxlength="12" id="UserName">
    <label for="PassWord">Password:</label>
    <input type="password" name="PassWord" size="12" maxlength="12">
    <input type="submit" class="margin-top-twenty" value="Submit">
  </form>
{% endblock %}
