{% extends "base.phtml" %}

{% block content %}
  <div align="CENTER">
  <span>Welcome {{ user }}</span>
  <table>
    <thead>
      <tr>
        <th>Sl no.</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Reason</th>
        <th>Approved</th>
      </tr>
    </thead>
    <tbody>
      {% for leave in leaves %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ leave.start_date }}</td>
          <td>{{ leave.end_date }}</td>
          <td>{{ leave.reason }}</td>
          <td>{{ leave.status }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}