{% extends "base.phtml" %}

{% block content %}
  <div align="CENTER">
  <span>Welcome {{ user }}</span>
  <div class="border-five-hundred margin-top-fifty">
  <legend id="login-legend" class="left">Your Leaves</legend>
  {% if leaves %}
  <table cellpadding="10" class="center-text margin-top-fifty margin-bottom-twenty">
    <thead>
      <tr>
        <th>Sl no.</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Reason</th>
        <th>Approved</th>
      </tr>
    </thead>
    <tbody>
      {% for leave in leaves %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ leave.start_date }}</td>
          <td>{{ leave.end_date }}</td>
          <td>{{ leave.reason }}</td>
          <td>{{ leave.status }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <div class="margin-top-twenty">You have not apply for any leaves yet.</div>
  {% endif %}
  </div>
</div>
{% endblock %}
